amqp:
  admin:
    auto-create: ${AMQP_ADMIN_AUTO_CREATE:true}
  host: ${AMQP_RABBIT_HOST:rabbit}
  port: ${AMQP_RABBIT_PORT:5672}
  username: ${AMQP_RABBIT_USERNAME:adm_videos}
  password: ${AMQP_RABBIT_PASSWORD:123456}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: ${DATABASE_MYSQL_SCHEMA:adm_videos}
  url: ${DATABASE_MYSQL_UR:mysql:3306}

keycloak:
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://keycloak:8443}

  spring:
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none