version: '3.8'

services:
  app:
    container_name: adm_videos_app
    #    image: sidartasilva/fc3-admin-catalogo-videos-java:main-1
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true